---
all:
  children:
    CVP:
      hosts:
        cvaas:
          ansible_httpapi_host: www.cv-staging.corp.arista.io
          ansible_host: www.cv-staging.corp.arista.io
          ansible_user: cvaas
          ansible_password: "{{ lookup('file', '/Users/tamas/tokens/cvaas.tok')}}"
          ansible_become: True
          ansible_become_method: enable
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: False
          ansible_network_os: eos
          ansible_httpapi_port: 443
        cv_server:
          ansible_httpapi_host: 10.83.12.79
          ansible_host: 10.83.12.79
          ansible_user: cvpadmin
          ansible_password: arastra
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: False
          ansible_network_os: eos
          ansible_httpapi_port: 443
          ansible_python_interpreter: $(which python3)
